### ISSUE TITLE
Excellent configs

### ISSUE THREAD

**Issue by zenny** [sunnyhasija/DOOMEmacs#1]
@sunnyhasija Thanks for posting your configuration. Appears relevant to researchers. :D

Would you mind posting here or somewhere your workflow of note-taking and academic writing using your configuration? Appreciate that.

Cheers, and stay safe,
/z

**Comment by sunnyhasija** [comment]
Hey @zenny , 

I have updated the Readme with a blurb about my typical workflow. When I have some more time, I hope to add some more details.

Thank you for your interest.

**Comment by zenny** [comment]
> Hey @zenny ,
> 
> I have updated the Readme with a blurb about my typical workflow. When I have some more time, I hope to add some more details.
> 
> Thank you for your interest.

@sunnyhasija I just came across https://www.reddit.com/r/emacs/comments/hltl69/org_roam_for_academics_demo/ where you have categorically specified the workflow of notetaking. Thanks a zillion and keep yourself safe.

Cheers,
/z
