### ISSUE TITLE
[SOLVED] Oversight? `nov` is disabled in `packages.el`, yet defined in `init.el!? duplicate entries?!

### ISSUE THREAD

**Issue by zenny** [sunnyhasija/DOOMEmacs#2]
Hi @sunnyhasija 

1. Was it an oversight with the last  that `nov` is disabled in `packages.el (https://github.com/sunnyhasija/DOOMEmacs/blob/902c49a8399cdaae7add0dc996602dd3e2d2b6a2/packages.el#L59), yet enabled in https://github.com/sunnyhasija/DOOMEmacs/blob/902c49a8399cdaae7add0dc996602dd3e2d2b6a2/init.el#L177.

```
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
```

2. Likewise, a new file `custom.el` has been added (https://github.com/sunnyhasija/DOOMEmacs/blob/master/custom.el) which has duplicate entries as in `config.el` from https://github.com/sunnyhasija/DOOMEmacs/blob/902c49a8399cdaae7add0dc996602dd3e2d2b6a2/config.el#L384 onwards that read:

```
 '(org-journal-date-format "%A, %d %B %Y" t)
 '(org-journal-date-prefix "#+TITLE: " t)
 '(org-journal-dir "~/Dropbox/Org/Daily/" t)
 '(org-journal-file-format "%Y-%m-%d.org" t)
 '(package-selected-packages (quote (org-fancy-priorities))))
```

Just wondering? Cheers, and stay safe,
/z

**Comment by sunnyhasija** [comment]
Hey @zenny ,

Thank you for catching the oversight in init.el. I have commented out nov, as I do not plan on using it. Org-Noter works better for me, and I converted epubs to PDF using calibre now. 

As for custom.el, that is autogenerated by org-journal, and I *think* is used by it.
