### ISSUE TITLE
company-org-roam configuration + articles.org?

### ISSUE THREAD

**Issue by Ziip-dev** [sunnyhasija/DOOMEmacs#7]
Hello,

Thanks a lot for this guide, I need to clarify two things though as I struggle to understand all the mechanics of your config:

- I went through your entire config files but I found no clue of where you set up `company-org-roam` backend as you describe in your reddit post. For what I understand, but I might be wrong, this needs to be explicitly configured to become active when entering `org-roam-mode`.
- secondly, you set up this file "~/Dropbox/Org/references/articles.org" as `org-ref-bibliography-notes` and `bibtex-completion-notes-path`. Does it have any reason to exist as you use a `references/notes/` directory to store everything with org-roam?

**Comment by sunnyhasija** [comment]
Hey @Ziip-dev 

1) I did not need to configure `company-org-roam` to have it work. I can investigate this weekend. 
2) That file doesn't need to exist, its an artifact from when I was not using org-roam. Thanks for bringing it up, I will clean it up.

**Comment by Ziip-dev** [comment]
Thank you for the details :)
Please can you keep me updated if you find out how `company-org-roam` automatically gets activated? It never is in my case when I enter a roam buffer

**Comment by sunnyhasija** [comment]
@Ziip-dev after investigation, I found that `company-mode` needs to be activated for `company-org-roam` to work. I have company enabled in my init.el  under `:completion`. So everytime I start emacs, company is already started and therefore `company-org-roam` works. 

Hope this answers your question.
